selectors = {
    'email': '#CustomerEmail',
    'password': '#CustomerPassword',
    'login_button': '#customer_login > div > input',
    'sizes_box': '#SingleOptionSelector-0',
    'add_to_cart_button': '#shopify-section-product > section > div.product__shop > form > button',
    'address_frame': '#Intrnl_CO_Container',
    'first_name': '#CheckoutData_BillingFirstName',
    'last_name': '#CheckoutData_BillingLastName',
    'email_cart': '#CheckoutData_Email',
    'country_box': '#BillingCountryID',
    'address_line1': '#CheckoutData_BillingAddress1',
    'address_line2': '#CheckoutData_BillingAddress2',
    'city': '#BillingCity',
    'postcode': '#BillingZIP',
    'mobile': '#CheckoutData_BillingPhone',
    'add_alt_address': '#newShipping',
    'alt_first_name': '#CheckoutData_ShippingFirstName',
    'alt_last_name': '#CheckoutData_ShippingLastName',
    'alt_country_box': '#ShippingCountryID',
    'alt_address_line1': '#CheckoutData_ShippingAddress1',
    'alt_address_line2': '#CheckoutData_ShippingAddress2',
    'alt_city': '#ShippingCity',
    'alt_postcode': '#ShippingZIP',
    'alt_mobile': '#CheckoutData_ShippingPhone',
    'payment_frame': '#secureWindow',
    'card_number': '#cardNum',
    'exp_month': '#cardExpiryMonth',
    'exp_year': '#cardExpiryYear',
    'cvv': '#cvdNumber',
    'order_button': '#btnPay'
}
